name: punch_list_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  english_words: ^3.1.0
  intl: ^0.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^1.6.24
  flutter_tags: "^0.4.9+1"
  sqflite: ^1.3.0
  uuid: ^2.2.2
  provider: ^4.3.3
  image_picker: ^0.6.7+22
  flutter_slidable: ^0.5.7
  flutter_email_sender: ^4.0.0
  pdf: ^2.0.0
  pdf_viewer_plugin: ^1.1.1
  permission_handler: ^5.1.0+2
  image_gallery_saver: ^1.6.7
  admob_flutter: ^1.0.1
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  flutter_launcher_icons: ^0.8.1
  flutter_overboard: ^1.1.5
  shared_preferences: ^0.5.7+1
flutter_icons:
  android: true
  ios: true
  image_path: "lib/image/icon.png"
flutter:
  assets:
    - assets/imgTutorial1.png
    - assets/imgTutorial2.png
    - assets/font/ipagp.ttf
  uses-material-design: true

